# Generated by Django 4.1.3 on 2023-01-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desgination', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/pics/administrative')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hounours_course_date', models.CharField(max_length=100)),
                ('program_course_date', models.CharField(max_length=100)),
                ('merit_publish_date', models.CharField(max_length=100)),
                ('carrer_counceling_date', models.CharField(max_length=100)),
                ('fees_payment', models.CharField(max_length=100)),
                ('document_verification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_fee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desgination', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/pics/faculty')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desgination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desgination', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/pics/lib')),
                ('mail_id', models.EmailField(max_length=254)),
                ('whatsapp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desgination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media/pics/gallary')),
                ('img2', models.ImageField(upload_to='media/pics/gallary')),
                ('img3', models.ImageField(upload_to='media/pics/gallary')),
                ('img4', models.ImageField(upload_to='media/pics/gallary')),
                ('img5', models.ImageField(upload_to='media/pics/gallary')),
                ('img6', models.ImageField(upload_to='media/pics/gallary')),
                ('img7', models.ImageField(upload_to='media/pics/gallary')),
                ('img8', models.ImageField(upload_to='media/pics/gallary')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle_name', models.CharField(max_length=30)),
                ('img1', models.ImageField(upload_to='media/pics/principle')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media/pics/slider')),
                ('img2', models.ImageField(upload_to='media/pics/slider')),
                ('img3', models.ImageField(upload_to='media/pics/slider')),
                ('img4', models.ImageField(upload_to='media/pics/slider')),
                ('img5', models.ImageField(upload_to='media/pics/slider')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=50)),
                ('desgination', models.CharField(max_length=50)),
            ],
        ),
    ]
