# Generated by Django 4.1.3 on 2023-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicQueryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='facultymembers',
            name='qualification',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultymembers',
            name='specialization',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
