# Generated by Django 4.1.3 on 2023-01-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_publicqueryform_facultymembers_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymembers',
            name='image',
            field=models.ImageField(upload_to='academic/pics/faculty'),
        ),
    ]
