# Generated by Django 4.1.3 on 2023-01-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_facultymembers_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultymembers',
            old_name='image',
            new_name='img',
        ),
    ]
