# Generated by Django 4.1.3 on 2023-01-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_librarian_desgination_alter_librarian_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('courseseats', models.CharField(max_length=30)),
            ],
        ),
    ]
