# Generated by Django 4.1.3 on 2023-01-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionnotice',
            name='year',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
