# Generated by Django 4.1.3 on 2023-01-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_admissionnotice_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=1000)),
                ('books_in_digit', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_catagory', models.CharField(max_length=1000)),
                ('books_available', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_public_access_catalog', models.CharField(max_length=1000)),
                ('dbm_whatsapp_group_link1', models.CharField(max_length=1000)),
                ('dbm_whatsapp_group_link2', models.CharField(max_length=1000)),
                ('dbm_lib_whatsapp_group_link3', models.CharField(max_length=1000)),
                ('wbclolr', models.CharField(max_length=1000)),
                ('ndli', models.CharField(max_length=1000)),
                ('internet_archive', models.CharField(max_length=1000)),
            ],
        ),
    ]
