# Generated by Django 4.1.3 on 2023-01-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_canteen_carrerguidence_mamangementmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='year',
            field=models.CharField(default=2023, max_length=10),
            preserve_default=False,
        ),
    ]
