# Generated by Django 4.1.3 on 2023-01-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_computercenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalander',
            name='description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
