# Generated by Django 4.1.3 on 2023-01-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0018_indexalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='img5',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
