# Generated by Django 4.1.3 on 2023-01-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_remove_sliderimage_img2_remove_sliderimage_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_details', models.CharField(max_length=200)),
                ('notice_link', models.CharField(blank=True, max_length=200, null=True)),
                ('notice_file', models.FileField(blank=True, null=True, upload_to='media/notice/files')),
            ],
        ),
    ]
