# Generated by Django 4.1.3 on 2023-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0021_rename_notice_link_notice_notice_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
    ]
