# Generated by Django 4.1.3 on 2023-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
