# Generated by Django 4.1.3 on 2023-01-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0023_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallary',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='photogallary',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='photogallary',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='photogallary',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='photogallary',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='photogallary',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='photogallary',
            name='img8',
        ),
    ]
