# Generated by Django 4.1.3 on 2023-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_rename_first_name_publicqueryform_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionnotice',
            name='carrer_counceling_date',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='document_verification',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='fees_payment',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='hounours_course_date',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='merit_publish_date',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='program_course_date',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='year',
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='file',
            field=models.FileField(default=0, upload_to='media/admission-notice/file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='label',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
