# Generated by Django 4.1.3 on 2023-01-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0027_remove_admissionnotice_carrer_counceling_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicqueryform',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='file',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='label',
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='carrer_counceling_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='document_verification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='fees_payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='hounours_course_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='merit_publish_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='program_course_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='year',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
