# Generated by Django 4.1.3 on 2023-01-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0028_rename_name_publicqueryform_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicqueryform',
            old_name='first_name',
            new_name='name',
        ),
    ]
