# Generated by Django 4.1.3 on 2023-01-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_rename_first_name_publicqueryform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
