# Generated by Django 4.1.3 on 2023-01-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0030_notice_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1000)),
            ],
        ),
    ]
