# Generated by Django 4.1.3 on 2023-01-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0033_rename_dbm_lib_whatsapp_group_link3_resource_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionQuery',
        ),
    ]
