# Generated by Django 4.1.3 on 2023-02-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0038_courses_course_main_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_main_subject_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
