# Generated by Django 4.1.3 on 2023-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0039_alter_courses_course_main_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='about',
            field=models.CharField(max_length=100000000, null=True),
        ),
    ]
