# Generated by Django 4.1.3 on 2023-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0040_departments_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='year',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
