# Generated by Django 4.1.3 on 2023-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0044_indexsliderimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccalander',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='academiccalander',
            name='link',
        ),
        migrations.AddField(
            model_name='academiccalander',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/academic-calender/'),
        ),
    ]
