# Generated by Django 4.1.3 on 2023-02-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0047_alter_ext_rep_desgination_alter_ext_rep_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexalert',
            name='file',
            field=models.FileField(default=0, max_length=1000000, upload_to=''),
            preserve_default=False,
        ),
    ]
