# Generated by Django 4.1.3 on 2023-02-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0048_indexalert_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexalert',
            name='link',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='indexalert',
            name='file',
            field=models.FileField(max_length=1000000, null=True, upload_to=''),
        ),
    ]
