# Generated by Django 4.1.3 on 2023-02-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0050_eresources_resource_link_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eresources',
            name='Resource_link',
            field=models.CharField(blank=True, default='/', max_length=300, null=True),
        ),
    ]
