# Generated by Django 4.1.3 on 2023-01-16 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=1000)),
                ('semester', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('routine_pdf', models.FileField(upload_to='media/files/routine')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=1000)),
                ('rollno', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('semester', models.CharField(max_length=1000)),
                ('semester_marksheet', models.CharField(max_length=1000)),
                ('semester_registration', models.CharField(max_length=1000)),
                ('semester_routine', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSignup',
            fields=[
                ('id', models.BigAutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Rollno', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000000)),
            ],
        ),
    ]
