# Generated by Django 4.1.3 on 2023-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_routine_marksheet_pdf_routine_routine_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=1000)),
                ('semester', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('admit_pdf', models.FileField(upload_to='media/files/registration')),
                ('roll', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=1000)),
                ('semester', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('registration_pdf', models.FileField(upload_to='media/files/registration')),
                ('roll', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='studentdata',
            name='semester_admit',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='semester_marksheet',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='semester_registration',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='semester_routine',
            field=models.FileField(upload_to=''),
        ),
    ]
