# Generated by Django 4.1.3 on 2023-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_registerrollno_studentsignup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerrollno',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='registerrollno',
            name='year',
        ),
        migrations.AlterField(
            model_name='registerrollno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
