# Generated by Django 4.1.3 on 2023-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_notification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=1000)),
                ('semester', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('syllabus_pdf', models.FileField(upload_to='media/files/admitcard')),
                ('course_type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='label',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
