# Generated by Django 4.1.3 on 2023-02-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_delete_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentfriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
